set mouse-=a
"set number
set ruler
syntax on
set nowrap
set pastetoggle=<F2>

" allow backspacing over everything in insert mode
"set backspace=indent,eol,start

filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab
